package vista;

import controlador.eventos.CementerioController;

public class VistaCementerio extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaCementerio.class.getName());

    public VistaCementerio() {
        initComponents();
        this.setResizable(false);
        // Instanciamos el controlador pasándole esta vista, igual que en el Bestiario
        new CementerioController(this);
    }

    public javax.swing.JTable getTabla1() {
        return tabla1;
    }

    public javax.swing.JTable getTabla2() {
        return tabla2;
    }

    public javax.swing.JScrollPane getScrollPanel1() {
        return scrollPanel1;
    }

    public javax.swing.JScrollPane getScrollPanel2() {
        return scrollPanel2;
    }

    public javax.swing.JButton getAnterior() {
        return anterior;
    }

    public javax.swing.JButton getSiguiente() {
        return siguiente;
    }

    public javax.swing.JButton getVolverInicio() {
        return volverInicio;
    }

    /**
     * Método exclusivamente visual: Recibe los textos preparados y los dibuja
     * en los JLabels.
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverInicio = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        scrollPanel1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        scrollPanel2 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        cementerioFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(55, 55, 60));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volverInicio.setBackground(new java.awt.Color(102, 102, 102));
        volverInicio.setFont(new java.awt.Font("Cinzel", 1, 18)); // NOI18N
        volverInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        volverInicio.setBorderPainted(false);
        volverInicio.setContentAreaFilled(false);
        getContentPane().add(volverInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 240, 90));

        anterior.setBackground(new java.awt.Color(130, 112, 56));
        anterior.setFont(new java.awt.Font("Cinzel", 1, 18)); // NOI18N
        anterior.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        anterior.setBorderPainted(false);
        anterior.setContentAreaFilled(false);
        anterior.addActionListener(this::anteriorActionPerformed);
        getContentPane().add(anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 110, 110));

        siguiente.setBackground(new java.awt.Color(130, 112, 56));
        siguiente.setFont(new java.awt.Font("Cinzel", 1, 18)); // NOI18N
        siguiente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        siguiente.setBorderPainted(false);
        siguiente.setContentAreaFilled(false);
        siguiente.addActionListener(this::siguienteActionPerformed);
        getContentPane().add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 140, 120));

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPanel1.setViewportView(tabla1);

        getContentPane().add(scrollPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 260, 240));

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPanel2.setViewportView(tabla2);

        getContentPane().add(scrollPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 260, 240));

        cementerioFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondosMenus/FondoCementerio.jpg"))); // NOI18N
        getContentPane().add(cementerioFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anteriorActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siguienteActionPerformed

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new VistaCementerio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior;
    private javax.swing.JLabel cementerioFondo;
    private javax.swing.JScrollPane scrollPanel1;
    private javax.swing.JScrollPane scrollPanel2;
    private javax.swing.JButton siguiente;
    private javax.swing.JTable tabla1;
    private javax.swing.JTable tabla2;
    private javax.swing.JButton volverInicio;
    // End of variables declaration//GEN-END:variables
}
