package vista;

/**
 * Interfaz gráfica encargada del menú de creación y selección de personaje.
 * Permite al usuario introducir un nombre de héroe, seleccionar entre las
 * diferentes clases disponibles (Guerrero, Mago, Tanque, Pícaro, Arquero) e
 * iniciar una nueva run.
 */
public class VistaMenuCreacionPersonaje extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaMenuCreacionPersonaje.class.getName());

    /**
     * Constructor de la vista. Inicializa todos los componentes de la interfaz,
     * deshabilita el redimensionamiento de la ventana e instancia su respectivo
     * controlador para delegar la gestión lógica de los eventos según el patrón
     * MVC.
     */
    public VistaMenuCreacionPersonaje() {
        initComponents();
        this.setResizable(false);

        // [MVC ESTRICTO]: Instancia el controlador específico pasándose a sí mismo
        new controlador.eventos.MenuCreacionPersonajeController(this);
    }

    /**
     * Proporciona acceso directo al botón asociado a la clase Guerrero.
     *
     * @return El componente JButton para la clase Guerrero.
     */
    public javax.swing.JButton getBtnGuerrero() {
        return btnGuerrero;
    }

    /**
     * Proporciona acceso directo al botón asociado a la clase Tanque.
     *
     * @return El componente JButton para la clase Tanque.
     */
    public javax.swing.JButton getBtnTanque() {
        return btnTanque;
    }

    /**
     * Proporciona acceso directo al botón asociado a la clase Mago.
     *
     * @return El componente JButton para la clase Mago.
     */
    public javax.swing.JButton getBtnMago() {
        return btnMago;
    }

    /**
     * Proporciona acceso directo al botón asociado a la clase Pícaro.
     *
     * @return El componente JButton para la clase Pícaro.
     */
    public javax.swing.JButton getBtnPicaro() {
        return btnPicaro;
    }

    /**
     * Proporciona acceso directo al botón asociado a la clase Arquero.
     *
     * @return El componente JButton para la clase Arquero.
     */
    public javax.swing.JButton getBtnArquero() {
        return btnArquero;
    }

    /**
     * Proporciona acceso directo al botón encargado de comenzar la partida.
     *
     * @return El componente JButton para iniciar la run.
     */
    public javax.swing.JButton getBtnRun() {
        return btnRun;
    }

    /**
     * Proporciona acceso directo al botón para regresar al menú inicial.
     *
     * @return El componente JButton para volver atrás.
     */
    public javax.swing.JButton getVolverInicio() {
        return volverInicio;
    }

    /**
     * Proporciona acceso al campo de texto donde el usuario introduce el nombre
     * de su personaje.
     *
     * @return El componente JTextField con el nombre introducido.
     */
    public javax.swing.JTextField getTxtInputField() {
        return jTextField1;
    }

    /**
     * Modifica el contenido de la etiqueta de texto encargada de mostrar de
     * forma visual la clase que el jugador tiene seleccionada actualmente.
     *
     * @param textoClase Cadena de texto que describe la clase seleccionada (ej.
     * "Guerrero").
     */
    public void setLabelClaseSeleccionada(String textoClase) {
        seleccionPersonaje.setText(textoClase);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuerrero = new javax.swing.JButton();
        btnTanque = new javax.swing.JButton();
        btnMago = new javax.swing.JButton();
        btnPicaro = new javax.swing.JButton();
        btnArquero = new javax.swing.JButton();
        btnRun = new javax.swing.JButton();
        txtNombre = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        seleccionPersonaje = new javax.swing.JLabel();
        volverInicio = new javax.swing.JButton();
        personajesFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(55, 55, 60));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuerrero.setBackground(new java.awt.Color(30, 32, 35));
        btnGuerrero.setFont(new java.awt.Font("MedievalSharp", 1, 18)); // NOI18N
        btnGuerrero.setForeground(new java.awt.Color(255, 255, 255));
        btnGuerrero.setText("Guerrero");
        btnGuerrero.setBorderPainted(false);
        btnGuerrero.setContentAreaFilled(false);
        btnGuerrero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuerrero.setDefaultCapable(false);
        btnGuerrero.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnGuerrero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 150, 350));

        btnTanque.setBackground(new java.awt.Color(30, 32, 35));
        btnTanque.setFont(new java.awt.Font("MedievalSharp", 1, 18)); // NOI18N
        btnTanque.setForeground(new java.awt.Color(255, 255, 255));
        btnTanque.setText("Tanque");
        btnTanque.setBorderPainted(false);
        btnTanque.setContentAreaFilled(false);
        btnTanque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTanque.setDefaultCapable(false);
        btnTanque.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnTanque, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 140, 320));

        btnMago.setBackground(new java.awt.Color(30, 32, 35));
        btnMago.setFont(new java.awt.Font("MedievalSharp", 1, 18)); // NOI18N
        btnMago.setForeground(new java.awt.Color(255, 255, 255));
        btnMago.setText("Mago");
        btnMago.setBorderPainted(false);
        btnMago.setContentAreaFilled(false);
        btnMago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMago.setDefaultCapable(false);
        btnMago.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnMago, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 120, 330));

        btnPicaro.setBackground(new java.awt.Color(30, 32, 35));
        btnPicaro.setFont(new java.awt.Font("MedievalSharp", 1, 18)); // NOI18N
        btnPicaro.setForeground(new java.awt.Color(255, 255, 255));
        btnPicaro.setText("Picaro");
        btnPicaro.setBorderPainted(false);
        btnPicaro.setContentAreaFilled(false);
        btnPicaro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPicaro.setDefaultCapable(false);
        btnPicaro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnPicaro, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 140, 330));

        btnArquero.setBackground(new java.awt.Color(30, 32, 35));
        btnArquero.setFont(new java.awt.Font("MedievalSharp", 1, 18)); // NOI18N
        btnArquero.setForeground(new java.awt.Color(255, 255, 255));
        btnArquero.setText("Arquero");
        btnArquero.setBorderPainted(false);
        btnArquero.setContentAreaFilled(false);
        btnArquero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnArquero.setDefaultCapable(false);
        btnArquero.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnArquero, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 220, 120, 360));

        btnRun.setBackground(new java.awt.Color(30, 32, 35));
        btnRun.setFont(new java.awt.Font("MedievalSharp", 1, 18)); // NOI18N
        btnRun.setForeground(new java.awt.Color(255, 255, 255));
        btnRun.setText("Iniciar Run");
        btnRun.setBorderPainted(false);
        btnRun.setContentAreaFilled(false);
        btnRun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRun.setDefaultCapable(false);
        btnRun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRun.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnRun.addActionListener(this::btnRunActionPerformed);
        getContentPane().add(btnRun, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 430, 130, 230));

        txtNombre.setFont(new java.awt.Font("MedievalSharp", 1, 48)); // NOI18N
        txtNombre.setText("Nombre");
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, -1));

        jTextField1.setBackground(new java.awt.Color(185, 177, 152));
        jTextField1.setFont(new java.awt.Font("MedievalSharp", 0, 12)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 320, 30));

        seleccionPersonaje.setFont(new java.awt.Font("Cinzel", 1, 18)); // NOI18N
        getContentPane().add(seleccionPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, -1));

        volverInicio.setBackground(new java.awt.Color(102, 102, 102));
        volverInicio.setFont(new java.awt.Font("Cinzel", 1, 18)); // NOI18N
        volverInicio.setText("Volver");
        volverInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(volverInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 110, 60));

        personajesFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondosMenus/FondoSeleccionPersonaje.jpg"))); // NOI18N
        getContentPane().add(personajesFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new VistaMenuCreacionPersonaje().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArquero;
    private javax.swing.JButton btnGuerrero;
    private javax.swing.JButton btnMago;
    private javax.swing.JButton btnPicaro;
    private javax.swing.JButton btnRun;
    private javax.swing.JButton btnTanque;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel personajesFondo;
    private javax.swing.JLabel seleccionPersonaje;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JButton volverInicio;
    // End of variables declaration//GEN-END:variables
}
