package vista;

public class VistaMenuInicial extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaMenuInicial.class.getName());

    public VistaMenuInicial() {
        initComponents();
        this.setResizable(false);

        // [MVC ESTRICTO]: El control se cede por completo al controlador específico
        new controlador.eventos.MenuInicialController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevaPartida = new javax.swing.JButton();
        btnReanudarPartida = new javax.swing.JButton();
        btnBestiario = new javax.swing.JButton();
        btnCementerio = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        ladrillosFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(55, 55, 60));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevaPartida.setBackground(new java.awt.Color(30, 32, 35));
        btnNuevaPartida.setFont(new java.awt.Font("MedievalSharp", 1, 18)); // NOI18N
        btnNuevaPartida.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaPartida.setBorderPainted(false);
        btnNuevaPartida.setContentAreaFilled(false);
        btnNuevaPartida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevaPartida.setDefaultCapable(false);
        btnNuevaPartida.setPreferredSize(new java.awt.Dimension(250, 75));
        getContentPane().add(btnNuevaPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 160, 220));

        btnReanudarPartida.setBackground(new java.awt.Color(30, 32, 35));
        btnReanudarPartida.setFont(new java.awt.Font("MedievalSharp", 1, 18)); // NOI18N
        btnReanudarPartida.setForeground(new java.awt.Color(255, 255, 255));
        btnReanudarPartida.setBorderPainted(false);
        btnReanudarPartida.setContentAreaFilled(false);
        btnReanudarPartida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReanudarPartida.setDefaultCapable(false);
        btnReanudarPartida.setPreferredSize(new java.awt.Dimension(250, 75));
        getContentPane().add(btnReanudarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 190, 150));

        btnBestiario.setBackground(new java.awt.Color(30, 32, 35));
        btnBestiario.setFont(new java.awt.Font("MedievalSharp", 1, 18)); // NOI18N
        btnBestiario.setForeground(new java.awt.Color(255, 255, 255));
        btnBestiario.setBorderPainted(false);
        btnBestiario.setContentAreaFilled(false);
        btnBestiario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBestiario.setDefaultCapable(false);
        getContentPane().add(btnBestiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 140, 210));

        btnCementerio.setBackground(new java.awt.Color(30, 32, 35));
        btnCementerio.setFont(new java.awt.Font("MedievalSharp", 1, 18)); // NOI18N
        btnCementerio.setForeground(new java.awt.Color(255, 255, 255));
        btnCementerio.setBorderPainted(false);
        btnCementerio.setContentAreaFilled(false);
        btnCementerio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCementerio.setDefaultCapable(false);
        btnCementerio.addActionListener(this::btnCementerioActionPerformed);
        getContentPane().add(btnCementerio, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, 170, 240));

        btnSalir.setBackground(new java.awt.Color(30, 32, 35));
        btnSalir.setFont(new java.awt.Font("MedievalSharp", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setDefaultCapable(false);
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 500, 140, 160));

        ladrillosFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondosMenus/FondoMenuInicial.jpg"))); // NOI18N
        getContentPane().add(ladrillosFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCementerioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCementerioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCementerioActionPerformed

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new VistaMenuInicial().setVisible(true));
    }

    public javax.swing.JButton getBtnNuevaPartida() {
        return btnNuevaPartida;
    }

    public javax.swing.JButton getBtnReanudarPartida() {
        return btnReanudarPartida;
    }

    public javax.swing.JButton getBtnBestiario() {
        return btnBestiario;
    }

    public javax.swing.JButton getBtnCementerio() {
        return btnCementerio;
    }

    public javax.swing.JButton getBtnSalir() {
        return btnSalir;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBestiario;
    private javax.swing.JButton btnCementerio;
    private javax.swing.JButton btnNuevaPartida;
    private javax.swing.JButton btnReanudarPartida;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel ladrillosFondo;
    // End of variables declaration//GEN-END:variables
}
