package vista;

/**
 * Interfaz gráfica encargada de representar la pantalla de subida de nivel.
 * Muestra visualmente al jugador el incremento de los atributos de su héroe
 * comparando el estado anterior con las nuevas bonificaciones.
 */
public class VistaSubidaNivel extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaSubidaNivel.class.getName());

    /**
     * Constructor de la vista. Inicializa los componentes de la interfaz,
     * deshabilita el redimensionamiento, centra la ventana en la pantalla e
     * instancia su respectivo controlador.
     */
    public VistaSubidaNivel() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    // =========================================================================
    //  GETTERS PÚBLICOS EXIGIDOS POR EL MVC (Dan acceso externo al Controlador)
    // =========================================================================
    /**
     * Proporciona acceso al botón encargado de confirmar y cerrar la interfaz.
     *
     * @return El componente JButton para continuar la partida.
     */
    public javax.swing.JButton getBtnContinuar() {
        return btnContinuar;
    }

    /**
     * Proporciona acceso a la etiqueta encargada de mostrar el ataque del
     * héroe.
     *
     * @return El componente JLabel asociado al ataque.
     */
    public javax.swing.JLabel getTxtAtaque() {
        return txtAtaque;
    }

    /**
     * Proporciona acceso a la etiqueta encargada de mostrar la defensa del
     * héroe.
     *
     * @return El componente JLabel asociado a la defensa.
     */
    public javax.swing.JLabel getTxtDefensa() {
        return txtDefensa;
    }

    /**
     * Proporciona acceso a la etiqueta encargada de mostrar la estamina del
     * héroe.
     *
     * @return El componente JLabel asociado a la estamina.
     */
    public javax.swing.JLabel getTxtEstamina() {
        return txtEstamina;
    }

    /**
     * Proporciona acceso a la etiqueta encargada de mostrar los puntos de vida
     * del héroe.
     *
     * @return El componente JLabel asociado a la salud (HP).
     */
    public javax.swing.JLabel getTxtHp() {
        return txtHp;
    }

    /**
     * Proporciona acceso a la etiqueta encargada de mostrar el nivel actual del
     * héroe.
     *
     * @return El componente JLabel asociado al nivel.
     */
    public javax.swing.JLabel getTxtNivel() {
        return txtNivel;
    }

    /**
     * Proporciona acceso a la etiqueta encargada de mostrar la suerte del
     * héroe.
     *
     * @return El componente JLabel asociado a la suerte.
     */
    public javax.swing.JLabel getTxtSuerte() {
        return txtSuerte;
    }

    /**
     * Proporciona acceso a la etiqueta encargada de mostrar la velocidad del
     * héroe.
     *
     * @return El componente JLabel asociado a la velocidad.
     */
    public javax.swing.JLabel getTxtVelocidad() {
        return txtVelocidad;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNivel = new javax.swing.JLabel();
        txtHp = new javax.swing.JLabel();
        txtEstamina = new javax.swing.JLabel();
        txtAtaque = new javax.swing.JLabel();
        txtDefensa = new javax.swing.JLabel();
        txtVelocidad = new javax.swing.JLabel();
        txtSuerte = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        subidaNivelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(55, 55, 60));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNivel.setFont(new java.awt.Font("Cinzel", 1, 14)); // NOI18N
        txtNivel.setForeground(new java.awt.Color(255, 255, 255));
        txtNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNivel.setText("aaaaa");
        getContentPane().add(txtNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 560, 30));

        txtHp.setFont(new java.awt.Font("Cinzel", 1, 14)); // NOI18N
        txtHp.setForeground(new java.awt.Color(255, 255, 255));
        txtHp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHp.setText("aaaaa");
        txtHp.setToolTipText("");
        getContentPane().add(txtHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 560, 30));

        txtEstamina.setFont(new java.awt.Font("Cinzel", 1, 14)); // NOI18N
        txtEstamina.setForeground(new java.awt.Color(255, 255, 255));
        txtEstamina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEstamina.setText("aaaaa");
        getContentPane().add(txtEstamina, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 560, 30));

        txtAtaque.setFont(new java.awt.Font("Cinzel", 1, 14)); // NOI18N
        txtAtaque.setForeground(new java.awt.Color(255, 255, 255));
        txtAtaque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAtaque.setText("aaaaa");
        getContentPane().add(txtAtaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 560, 30));

        txtDefensa.setFont(new java.awt.Font("Cinzel", 1, 14)); // NOI18N
        txtDefensa.setForeground(new java.awt.Color(255, 255, 255));
        txtDefensa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDefensa.setText("aaaaa");
        getContentPane().add(txtDefensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 560, 30));

        txtVelocidad.setFont(new java.awt.Font("Cinzel", 1, 14)); // NOI18N
        txtVelocidad.setForeground(new java.awt.Color(255, 255, 255));
        txtVelocidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtVelocidad.setText("aaaaa");
        getContentPane().add(txtVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 560, 30));

        txtSuerte.setFont(new java.awt.Font("Cinzel", 1, 14)); // NOI18N
        txtSuerte.setForeground(new java.awt.Color(255, 255, 255));
        txtSuerte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSuerte.setText("aaaaa");
        getContentPane().add(txtSuerte, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 560, 30));

        btnContinuar.setBackground(new java.awt.Color(102, 102, 102));
        btnContinuar.setFont(new java.awt.Font("Cinzel", 1, 24)); // NOI18N
        btnContinuar.setText("CONTINUAR");
        btnContinuar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, -1, -1));

        subidaNivelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondosMenus/FondoSubidaNivel.jpg"))); // NOI18N
        getContentPane().add(subidaNivelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new VistaSubidaNivel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JLabel subidaNivelFondo;
    private javax.swing.JLabel txtAtaque;
    private javax.swing.JLabel txtDefensa;
    private javax.swing.JLabel txtEstamina;
    private javax.swing.JLabel txtHp;
    private javax.swing.JLabel txtNivel;
    private javax.swing.JLabel txtSuerte;
    private javax.swing.JLabel txtVelocidad;
    // End of variables declaration//GEN-END:variables
}
