package vista;

public class VistaBestiario extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaBestiario.class.getName());

    public VistaBestiario() {
        initComponents();
        this.setResizable(false);
        new controlador.eventos.BestiarioController(this);
    }

    /**
     * Método exclusivamente visual: Recibe los textos preparados y los dibuja
     * en los JLabels.
     */
    public void mostrarDatosMonstruo(String nombre, String titulo, String descHtml, String hp, String atq, String def, String vel, String rutaImagen) {
        txtNombreCriatura1.setText(nombre);
        tituloDescripcion1.setText(titulo);
        txtDescripcion1.setText(descHtml);

        hp1.setText(hp);
        ataque1.setText(atq);
        defensa1.setText(def);
        velocidad1.setText(vel);

        try {
            java.net.URL urlImagen = getClass().getResource(rutaImagen);
            if (urlImagen != null) {
                imagenMounstruo1.setIcon(new javax.swing.ImageIcon(urlImagen));
            } else {
                imagenMounstruo1.setIcon(null);
            }
        } catch (Exception imgEx) {
            System.err.println("Error al cargar icono en Vista: " + imgEx.getMessage());
            imagenMounstruo1.setIcon(null);
        }
    }

    // =========================================================================
    //  GETTERS PÚBLICOS EXIGIDOS POR EL MVC (Dan acceso externo a los botones)
    // =========================================================================
    public javax.swing.JButton getBasiliscoMenor() {
        return basiliscoMenor;
    }

    public javax.swing.JButton getCiclope() {
        return ciclope;
    }

    public javax.swing.JButton getFenixDeFuego() {
        return fenixDeFuego;
    }

    public javax.swing.JButton getGolemDePiedra() {
        return golemDePiedra;
    }

    public javax.swing.JButton getHarpia() {
        return Harpia;
    } // Ojo con la mayúscula de tu variable

    public javax.swing.JButton getHidraDeLerna() {
        return HidraDeLerna;
    } // Ojo con la mayúscula de tu variable

    public javax.swing.JButton getMinotauro() {
        return Minotauro;
    } // Ojo con la mayúscula de tu variable

    public javax.swing.JButton getQuimera() {
        return Quimera;
    } // Ojo con la mayúscula de tu variable

    public javax.swing.JButton getSombraEspectral() {
        return sombraEspectral;
    }

    public javax.swing.JButton getDragonAncestral() {
        return dragonAncestral;
    }

    public javax.swing.JButton getVolverInicio() {
        return volverInicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        libroIzquierda = new javax.swing.JPanel();
        txtIndice = new javax.swing.JLabel();
        separadorIzquierda1 = new javax.swing.JSeparator();
        basiliscoMenor = new javax.swing.JButton();
        ciclope = new javax.swing.JButton();
        fenixDeFuego = new javax.swing.JButton();
        golemDePiedra = new javax.swing.JButton();
        Harpia = new javax.swing.JButton();
        HidraDeLerna = new javax.swing.JButton();
        Minotauro = new javax.swing.JButton();
        Quimera = new javax.swing.JButton();
        sombraEspectral = new javax.swing.JButton();
        dragonAncestral = new javax.swing.JButton();
        libroDerecha = new javax.swing.JPanel();
        txtNombreCriatura1 = new javax.swing.JLabel();
        imagenMounstruo1 = new javax.swing.JLabel();
        tituloDescripcion1 = new javax.swing.JLabel();
        tituloEstadisticas1 = new javax.swing.JLabel();
        hp1 = new javax.swing.JLabel();
        separadorDerecha1 = new javax.swing.JSeparator();
        separadorDerecha2 = new javax.swing.JSeparator();
        ataque1 = new javax.swing.JLabel();
        defensa1 = new javax.swing.JLabel();
        velocidad1 = new javax.swing.JLabel();
        txtDescripcion1 = new javax.swing.JLabel();
        volverInicio = new javax.swing.JButton();
        libroFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(55, 55, 60));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        libroIzquierda.setFont(new java.awt.Font("MedievalSharp", 0, 12)); // NOI18N
        libroIzquierda.setOpaque(false);
        libroIzquierda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIndice.setFont(new java.awt.Font("Cinzel", 1, 24)); // NOI18N
        txtIndice.setText("Indice");
        libroIzquierda.add(txtIndice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        separadorIzquierda1.setForeground(new java.awt.Color(0, 0, 0));
        libroIzquierda.add(separadorIzquierda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 240, 10));

        basiliscoMenor.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        basiliscoMenor.setText("Esperando nombre . . .");
        basiliscoMenor.setContentAreaFilled(false);
        basiliscoMenor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        basiliscoMenor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        libroIzquierda.add(basiliscoMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 250, -1));

        ciclope.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        ciclope.setText("Esperando nombre . . .");
        ciclope.setContentAreaFilled(false);
        ciclope.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ciclope.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ciclope.addActionListener(this::ciclopeActionPerformed);
        libroIzquierda.add(ciclope, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 250, -1));

        fenixDeFuego.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        fenixDeFuego.setText("Esperando nombre . . .");
        fenixDeFuego.setContentAreaFilled(false);
        fenixDeFuego.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fenixDeFuego.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        libroIzquierda.add(fenixDeFuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 250, -1));

        golemDePiedra.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        golemDePiedra.setText("Esperando nombre . . .");
        golemDePiedra.setContentAreaFilled(false);
        golemDePiedra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        golemDePiedra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        libroIzquierda.add(golemDePiedra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 250, -1));

        Harpia.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        Harpia.setText("Esperando nombre . . .");
        Harpia.setContentAreaFilled(false);
        Harpia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Harpia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        libroIzquierda.add(Harpia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 250, -1));

        HidraDeLerna.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        HidraDeLerna.setText("Esperando nombre . . .");
        HidraDeLerna.setContentAreaFilled(false);
        HidraDeLerna.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HidraDeLerna.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        libroIzquierda.add(HidraDeLerna, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 250, -1));

        Minotauro.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        Minotauro.setText("Esperando nombre . . .");
        Minotauro.setContentAreaFilled(false);
        Minotauro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minotauro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        libroIzquierda.add(Minotauro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 250, -1));

        Quimera.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        Quimera.setText("Esperando nombre . . .");
        Quimera.setContentAreaFilled(false);
        Quimera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Quimera.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        libroIzquierda.add(Quimera, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 250, -1));

        sombraEspectral.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        sombraEspectral.setText("Esperando nombre . . .");
        sombraEspectral.setContentAreaFilled(false);
        sombraEspectral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sombraEspectral.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        libroIzquierda.add(sombraEspectral, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 250, -1));

        dragonAncestral.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        dragonAncestral.setText("Esperando nombre . . .");
        dragonAncestral.setContentAreaFilled(false);
        dragonAncestral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dragonAncestral.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dragonAncestral.addActionListener(this::dragonAncestralActionPerformed);
        libroIzquierda.add(dragonAncestral, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 250, -1));

        getContentPane().add(libroIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 340, 460));

        libroDerecha.setFont(new java.awt.Font("MedievalSharp", 0, 12)); // NOI18N
        libroDerecha.setOpaque(false);
        libroDerecha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreCriatura1.setFont(new java.awt.Font("Cinzel", 1, 24)); // NOI18N
        txtNombreCriatura1.setText("Esperando nombre");
        libroDerecha.add(txtNombreCriatura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        imagenMounstruo1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        libroDerecha.add(imagenMounstruo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 290, 130));

        tituloDescripcion1.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        tituloDescripcion1.setText("Esperando descripcion . . .");
        libroDerecha.add(tituloDescripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        tituloEstadisticas1.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        tituloEstadisticas1.setText("Estadisticas");
        libroDerecha.add(tituloEstadisticas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, -1));

        hp1.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        hp1.setText("Esperando hp . . .");
        libroDerecha.add(hp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        separadorDerecha1.setForeground(new java.awt.Color(0, 0, 0));
        libroDerecha.add(separadorDerecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 330, 10));

        separadorDerecha2.setForeground(new java.awt.Color(0, 0, 0));
        libroDerecha.add(separadorDerecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 330, 10));

        ataque1.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        ataque1.setText("Esperando ataque . . .");
        libroDerecha.add(ataque1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        defensa1.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        defensa1.setText("Esperando defensa . . .");
        libroDerecha.add(defensa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        velocidad1.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        velocidad1.setText("Esperando velocidad . . .");
        libroDerecha.add(velocidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        txtDescripcion1.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        txtDescripcion1.setText("Esperando descripcion . . .");
        libroDerecha.add(txtDescripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        getContentPane().add(libroDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 340, 450));

        volverInicio.setBackground(new java.awt.Color(102, 102, 102));
        volverInicio.setFont(new java.awt.Font("Cinzel", 1, 18)); // NOI18N
        volverInicio.setText("Volver");
        volverInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(volverInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 110, 60));

        libroFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondosMenus/FondoBestiario.jpg"))); // NOI18N
        getContentPane().add(libroFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ciclopeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciclopeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciclopeActionPerformed

    private void dragonAncestralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dragonAncestralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dragonAncestralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new VistaBestiario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Harpia;
    private javax.swing.JButton HidraDeLerna;
    private javax.swing.JButton Minotauro;
    private javax.swing.JButton Quimera;
    private javax.swing.JLabel ataque1;
    private javax.swing.JButton basiliscoMenor;
    private javax.swing.JButton ciclope;
    private javax.swing.JLabel defensa1;
    private javax.swing.JButton dragonAncestral;
    private javax.swing.JButton fenixDeFuego;
    private javax.swing.JButton golemDePiedra;
    private javax.swing.JLabel hp1;
    private javax.swing.JLabel imagenMounstruo1;
    private javax.swing.JPanel libroDerecha;
    private javax.swing.JLabel libroFondo;
    private javax.swing.JPanel libroIzquierda;
    private javax.swing.JSeparator separadorDerecha1;
    private javax.swing.JSeparator separadorDerecha2;
    private javax.swing.JSeparator separadorIzquierda1;
    private javax.swing.JButton sombraEspectral;
    private javax.swing.JLabel tituloDescripcion1;
    private javax.swing.JLabel tituloEstadisticas1;
    private javax.swing.JLabel txtDescripcion1;
    private javax.swing.JLabel txtIndice;
    private javax.swing.JLabel txtNombreCriatura1;
    private javax.swing.JLabel velocidad1;
    private javax.swing.JButton volverInicio;
    // End of variables declaration//GEN-END:variables
}
