package vista;

/**
 * Interfaz gráfica encargada de representar la pantalla de combate del juego.
 * Muestra dinámicamente las estadísticas de salud del héroe y del enemigo, el
 * piso actual, las ilustraciones de las criaturas y la bitácora con la
 * información del combate.
 */
public class VistaCombates extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaCombates.class.getName());

    /**
     * Constructor de la vista. Inicializa todos los componentes de la interfaz,
     * bloquea el redimensionamiento de la ventana, ajusta opacidades visuales y
     * vincula el controlador específico de la escena para gestionar los
     * eventos.
     */
    public VistaCombates() {
        initComponents();
        this.setResizable(false);
        this.getContentPane().setBackground(new java.awt.Color(55, 55, 60));
        personaje.setOpaque(false);

        // [MVC ESTRICTO]: El controlador específico se encarga de rellenar los datos iniciales y capturar eventos
        new controlador.eventos.CombatesController(this);
    }

    /**
     * Proporciona acceso directo a la etiqueta de texto encargada de mostrar el
     * piso actual.
     *
     * @return El componente JLabel que contiene el texto informativo del piso.
     */
    public javax.swing.JLabel getTxtPiso() {
        return txtPiso;
    }

    /**
     * Modifica el contenido de texto mostrado en la etiqueta informativa del
     * piso actual.
     *
     * @param textoPiso Cadena de texto formateada que describe el piso (ej.
     * "PISO 1").
     */
    public void setPiso(String textoPiso) {
        txtPiso.setText(textoPiso);
    }

    /**
     * Permite al controlador actualizar la información gráfica de la interfaz
     * en cada turno de la simulación sin romper el patrón de arquitectura MVC.
     *
     * * @param vidaH Cadena de texto con la vida actual y máxima del héroe.
     * @param vidaM Cadena de texto con la vida actual y máxima del monstruo.
     * @param infoCombate Mensaje informativo que detalla las acciones del
     * turno.
     * @param rutaImgMonstruo Ruta del recurso que apunta al gráfico ilustrativo
     * del enemigo.
     */
    public void refrescarDatosInterfaz(String vidaH, String vidaM, String infoCombate, String rutaImgMonstruo) {
        vidaPersonaje.setText(vidaH);
        vidaMonstruo1.setText(vidaM);
        txtInfo.setText(infoCombate);

        if (rutaImgMonstruo != null && !rutaImgMonstruo.isEmpty()) {
            try {
                java.net.URL url = getClass().getResource(rutaImgMonstruo);
                if (url != null) {
                    monstruo.setIcon(new javax.swing.ImageIcon(url));
                }
            } catch (Exception e) {
                System.err.println("Error cargando imagen de criatura en combate: " + e.getMessage());
            }
        }
    }

    /**
     * Proporciona acceso directo al botón de ataque utilizado en la interfaz.
     * Exigido por el modelo Vista-Controlador para la correcta delegación de
     * eventos de pulsación.
     *
     * @return El componente JButton configurado para realizar la acción de
     * ataque.
     */
    public javax.swing.JButton getBtnAtaque() {
        return ataque;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monstruo = new javax.swing.JLabel();
        personaje = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ataque = new javax.swing.JButton();
        vidaMonstruo1 = new javax.swing.JLabel();
        vidaPersonaje = new javax.swing.JLabel();
        txtInfo = new javax.swing.JLabel();
        txtPiso = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(55, 55, 60));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        monstruo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(monstruo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 450, 360));

        personaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Personajes/PersonajeGenericoEspalda.png"))); // NOI18N
        getContentPane().add(personaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 300, 520));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 543, 1230, 20));

        ataque.setBackground(new java.awt.Color(255, 51, 51));
        ataque.setFont(new java.awt.Font("Cinzel", 1, 36)); // NOI18N
        ataque.setText("ATACAR");
        ataque.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(ataque, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, 200, 110));

        vidaMonstruo1.setFont(new java.awt.Font("Cinzel", 1, 24)); // NOI18N
        vidaMonstruo1.setForeground(new java.awt.Color(29, 143, 29));
        vidaMonstruo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vidaMonstruo1.setText("vida/vida max");
        getContentPane().add(vidaMonstruo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, 470, -1));

        vidaPersonaje.setFont(new java.awt.Font("Cinzel", 1, 24)); // NOI18N
        vidaPersonaje.setForeground(new java.awt.Color(29, 143, 29));
        vidaPersonaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vidaPersonaje.setText("vida/vida max");
        getContentPane().add(vidaPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 410, -1));

        txtInfo.setFont(new java.awt.Font("Cinzel", 1, 24)); // NOI18N
        txtInfo.setForeground(new java.awt.Color(255, 255, 255));
        txtInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtInfo.setText("Esperando info");
        getContentPane().add(txtInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 810, 110));

        txtPiso.setFont(new java.awt.Font("Cinzel", 1, 24)); // NOI18N
        txtPiso.setForeground(new java.awt.Color(255, 255, 255));
        txtPiso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 330, 100));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new VistaCombates().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ataque;
    private javax.swing.JLabel fondo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel monstruo;
    private javax.swing.JLabel personaje;
    private javax.swing.JLabel txtInfo;
    private javax.swing.JLabel txtPiso;
    private javax.swing.JLabel vidaMonstruo1;
    private javax.swing.JLabel vidaPersonaje;
    // End of variables declaration//GEN-END:variables
}
