/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author rober
 */
public class VistaContinuarRun extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaContinuarRun.class.getName());

    /**
     * Creates new form VistaMenuInicial
     */
    public VistaContinuarRun() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        new controlador.eventos.ContinuarRunController(this);
    }

    public javax.swing.JButton getBtnContinuarRun() {
        return btnContinuarRun;
    }

    public javax.swing.JButton getBtnGuardarPartida() {
        return btnGuardarPartida;
    }

    public javax.swing.JButton getBtnSalir() {
        return btnSalir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnContinuarRun = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGuardarPartida = new javax.swing.JButton();
        fondoContinuarRun = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(55, 55, 60));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnContinuarRun.setBorderPainted(false);
        btnContinuarRun.setContentAreaFilled(false);
        getContentPane().add(btnContinuarRun, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 293, 380, 90));

        btnSalir.setToolTipText("");
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 407, 260, 70));

        btnGuardarPartida.setBorderPainted(false);
        btnGuardarPartida.setContentAreaFilled(false);
        getContentPane().add(btnGuardarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 230, 80));

        fondoContinuarRun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondosMenus/FondoMenuContinuarRun.jpg"))); // NOI18N
        getContentPane().add(fondoContinuarRun, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaContinuarRun().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuarRun;
    private javax.swing.JButton btnGuardarPartida;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel fondoContinuarRun;
    // End of variables declaration//GEN-END:variables
}
