package vista;

public class VistaMenuPartidas extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaMenuPartidas.class.getName());

    public VistaMenuPartidas() {
        initComponents();
        this.setResizable(false);
        new controlador.eventos.MenuPartidasController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombrePartida1 = new javax.swing.JTextField();
        btnCargarPartida = new javax.swing.JButton();
        btnBorrarPartida = new javax.swing.JButton();
        panelGuardados1 = new javax.swing.JPanel();
        txtPartida = new javax.swing.JLabel();
        txtHeroe = new javax.swing.JLabel();
        txtClase = new javax.swing.JLabel();
        txtPiso = new javax.swing.JLabel();
        txtNivel = new javax.swing.JLabel();
        panelGuardados2 = new javax.swing.JPanel();
        txtPartida1 = new javax.swing.JLabel();
        txtHeroe1 = new javax.swing.JLabel();
        txtClase1 = new javax.swing.JLabel();
        txtPiso1 = new javax.swing.JLabel();
        txtNivel1 = new javax.swing.JLabel();
        panelGuardados3 = new javax.swing.JPanel();
        txtPartida2 = new javax.swing.JLabel();
        txtHeroe2 = new javax.swing.JLabel();
        txtClase2 = new javax.swing.JLabel();
        txtPiso2 = new javax.swing.JLabel();
        txtNivel2 = new javax.swing.JLabel();
        volverInicio = new javax.swing.JButton();
        partidasFondo = new javax.swing.JLabel();

        txtNombrePartida1.setBackground(new java.awt.Color(185, 177, 152));
        txtNombrePartida1.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        txtNombrePartida1.setForeground(new java.awt.Color(255, 255, 255));
        txtNombrePartida1.setText("Esperando nombre");
        txtNombrePartida1.addActionListener(this::txtNombrePartida1ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(55, 55, 60));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCargarPartida.setBorderPainted(false);
        btnCargarPartida.setContentAreaFilled(false);
        getContentPane().add(btnCargarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 260, 120));

        btnBorrarPartida.setBorderPainted(false);
        btnBorrarPartida.setContentAreaFilled(false);
        btnBorrarPartida.addActionListener(this::btnBorrarPartidaActionPerformed);
        getContentPane().add(btnBorrarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, 260, 120));

        panelGuardados1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelGuardados1.setOpaque(false);
        panelGuardados1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 30));

        txtPartida.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        txtPartida.setText("Esperando partida . . .");
        panelGuardados1.add(txtPartida);

        txtHeroe.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        txtHeroe.setText("Esperando héroe . . .");
        panelGuardados1.add(txtHeroe);

        txtClase.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        txtClase.setText("Esperando clase . . .");
        panelGuardados1.add(txtClase);

        txtPiso.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        txtPiso.setText("Esperando piso . . .");
        panelGuardados1.add(txtPiso);

        txtNivel.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        txtNivel.setText("Esperando nivel . . .");
        panelGuardados1.add(txtNivel);

        getContentPane().add(panelGuardados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 200, 290));

        panelGuardados2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelGuardados2.setOpaque(false);
        panelGuardados2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 30));

        txtPartida1.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        txtPartida1.setText("Esperando partida . . .");
        panelGuardados2.add(txtPartida1);

        txtHeroe1.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        txtHeroe1.setText("Esperando héroe . . .");
        panelGuardados2.add(txtHeroe1);

        txtClase1.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        txtClase1.setText("Esperando clase . . .");
        panelGuardados2.add(txtClase1);

        txtPiso1.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        txtPiso1.setText("Esperando piso . . .");
        panelGuardados2.add(txtPiso1);

        txtNivel1.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        txtNivel1.setText("Esperando nivel . . .");
        panelGuardados2.add(txtNivel1);

        getContentPane().add(panelGuardados2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 200, 290));

        panelGuardados3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelGuardados3.setOpaque(false);
        panelGuardados3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 30));

        txtPartida2.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        txtPartida2.setText("Esperando partida . . .");
        panelGuardados3.add(txtPartida2);

        txtHeroe2.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        txtHeroe2.setText("Esperando héroe . . .");
        panelGuardados3.add(txtHeroe2);

        txtClase2.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        txtClase2.setText("Esperando clase . . .");
        panelGuardados3.add(txtClase2);

        txtPiso2.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        txtPiso2.setText("Esperando piso . . .");
        panelGuardados3.add(txtPiso2);

        txtNivel2.setFont(new java.awt.Font("Cinzel", 1, 12)); // NOI18N
        txtNivel2.setText("Esperando nivel . . .");
        panelGuardados3.add(txtNivel2);

        getContentPane().add(panelGuardados3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, 200, 290));

        volverInicio.setBackground(new java.awt.Color(102, 102, 102));
        volverInicio.setFont(new java.awt.Font("Cinzel", 1, 18)); // NOI18N
        volverInicio.setText("Volver");
        volverInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(volverInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 110, 60));

        partidasFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondosMenus/FondoMenuPartidasGuardadas.jpg"))); // NOI18N
        getContentPane().add(partidasFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarPartidaActionPerformed

    private void txtNombrePartida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePartida1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePartida1ActionPerformed

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new VistaMenuPartidas().setVisible(true));
    }

    public javax.swing.JButton getBtnCargarPartida() {
        return btnCargarPartida;
    }

    public javax.swing.JButton getBtnBorrarPartida() {
        return btnBorrarPartida;
    }

    public javax.swing.JButton getVolverInicio() {
        return volverInicio;
    }

    public javax.swing.JTextField getTxtNombrePartida() {
        return txtNombrePartida1;
    }

    public javax.swing.JLabel getTxtPartida() {
        return txtPartida;
    }

    public javax.swing.JLabel getTxtHeroe() {
        return txtHeroe;
    }

    public javax.swing.JLabel getTxtClase() {
        return txtClase;
    }

    public javax.swing.JLabel getTxtPiso() {
        return txtPiso;
    }

    public javax.swing.JLabel getTxtNivel() {
        return txtNivel;
    }

    // --- RANURA 2 ---
    public javax.swing.JLabel getTxtPartida1() {
        return txtPartida1;
    }

    public javax.swing.JLabel getTxtHeroe1() {
        return txtHeroe1;
    }

    public javax.swing.JLabel getTxtClase1() {
        return txtClase1;
    }

    public javax.swing.JLabel getTxtPiso1() {
        return txtPiso1;
    }

    public javax.swing.JLabel getTxtNivel1() {
        return txtNivel1;
    }

    // --- RANURA 3 ---
    public javax.swing.JLabel getTxtPartida2() {
        return txtPartida2;
    }

    public javax.swing.JLabel getTxtHeroe2() {
        return txtHeroe2;
    }

    public javax.swing.JLabel getTxtClase2() {
        return txtClase2;
    }

    public javax.swing.JLabel getTxtPiso2() {
        return txtPiso2;
    }

    public javax.swing.JLabel getTxtNivel2() {
        return txtNivel2;
    }

    public javax.swing.JPanel getPanelGuardados1() {
        return panelGuardados1;
    }

    public javax.swing.JPanel getPanelGuardados2() {
        return panelGuardados2;
    }

    public javax.swing.JPanel getPanelGuardados3() {
        return panelGuardados3;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarPartida;
    private javax.swing.JButton btnCargarPartida;
    private javax.swing.JPanel panelGuardados1;
    private javax.swing.JPanel panelGuardados2;
    private javax.swing.JPanel panelGuardados3;
    private javax.swing.JLabel partidasFondo;
    private javax.swing.JLabel txtClase;
    private javax.swing.JLabel txtClase1;
    private javax.swing.JLabel txtClase2;
    private javax.swing.JLabel txtHeroe;
    private javax.swing.JLabel txtHeroe1;
    private javax.swing.JLabel txtHeroe2;
    private javax.swing.JLabel txtNivel;
    private javax.swing.JLabel txtNivel1;
    private javax.swing.JLabel txtNivel2;
    private javax.swing.JTextField txtNombrePartida1;
    private javax.swing.JLabel txtPartida;
    private javax.swing.JLabel txtPartida1;
    private javax.swing.JLabel txtPartida2;
    private javax.swing.JLabel txtPiso;
    private javax.swing.JLabel txtPiso1;
    private javax.swing.JLabel txtPiso2;
    private javax.swing.JButton volverInicio;
    // End of variables declaration//GEN-END:variables
}
