package vista;

/**
 * Interfaz gráfica encargada de representar la pantalla de derrota del juego.
 * Se muestra cuando la salud del héroe llega a cero, permitiéndole interactuar
 * para gestionar el fin de la run y regresar a los menús correspondientes.
 */
public class VistaHasPerdido extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaHasPerdido.class.getName());

    /**
     * Constructor de la vista. Inicializa todos los componentes gráficos,
     * deshabilita el redimensionamiento de la interfaz e instancia su
     * respectivo controlador para delegar la gestión lógica de los eventos de
     * la escena.
     */
    public VistaHasPerdido() {
        initComponents();
        this.setResizable(false);

        // [MVC ESTRICTO]: Control delegado
        new controlador.eventos.HasPerdidoController(this);
    }

    /**
     * Proporciona acceso directo al botón de salida en la pantalla de derrota.
     * Exigido por el modelo Vista-Controlador para la correcta vinculación de
     * eventos.
     *
     * @return El componente JButton configurado para salir tras perder la
     * partida.
     */
    public javax.swing.JButton getBtnSalir() {
        return btnSalir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoHasPerdido = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(55, 55, 60));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoHasPerdido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondosMenus/FondoHasPerdido.jpg"))); // NOI18N
        getContentPane().add(fondoHasPerdido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 503, 220, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new VistaHasPerdido().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel fondoHasPerdido;
    // End of variables declaration//GEN-END:variables
}
